export const GET_CATEGORIES_PROCCESS = 'GET_CATEGORIES_PROCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_QUESTIONS_PROCCESS = 'GET_QUESTIONS_PROCCESS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';

export const SET_QUESTION_PAGINATION = 'SET_QUESTION_PAGINATION';

export const GET_USERS_PROCESS = 'GET_USERS_PROCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
